### ISSUE TITLE
CUDA Error: out of memory

### ISSUE THREAD

**Issue by 283958849** [AlexeyAB/Yolo_mark#19]
hi, I trained one of my picture, and copied all files you mentioned, and then I got "CUDA Error: out of memory" error when I execute this command in darknet:

**darknet detector train data/obj.data yolo-obj.cfg darknet19_448.conv.23**

I assure that memory of my PC is sufficient. Any help will be thanked!

**Comment by 283958849** [comment]
I changed the "subdivisions" to be 16 from 8, and error disappeared!

**Comment by AlexeyAB** [comment]
Hi, yes, you did the right thing - as described here: https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64: link
